### ISSUE TITLE
Настройка гаммы

### ISSUE THREAD

**Issue by mav745** [mav745/CyberGamer#2]
Движок применяет гамму глобально к драйверу. Гамма не сбрасываецо назад при выходе

**Comment by raub** [comment]
gl_vidnt.c 860
glConfig.deviceSupportsGamma = false;//GetDeviceGammaRamp( glw_state.hDC, glState.stateRamp );
или
cvar: gl_ignorehwgamma 1
приводят гамму в соответствие современному поведению ХЛ (софтварная гамма)
