### ISSUE TITLE
ping не обновляется (всегда 0)

### ISSUE THREAD

**Issue by raub** [mav745/CyberGamer#6]
При просмотре таблицы очков пинг всегда 0, у всех. Возможно при просмотре из HLTV это не так: sv_client.c,939 - они отрабатываются отдельно, а для игроков же пинг отправляется ТОЛЬКО при просмотре таблицы. Проверяется нажата ли клавиша IN_SCORE	(1<<15) у клиента, если да - обновить. Но клавиша никогда не приходит на момент проверки, в том числе другие клавиши.
Обнуление cl->lastcmd.buttons = 0; в sv_client.c,2158  и sv_game.c,3487 якобы для фикса множественной стрельбы(fires,"срабатываний"?) при лаге. Если убрать их, начинает работать пинг. Предлагаю не убирать, а сделать по умному, отключить только те биты которые надо. Какие?

**Comment by raub** [comment]
+ Проверяется нажата ли клавиша IN_SCORE, но на момент проверки клавиши сброшены (всегда пусто, вообще)

**Comment by mav745** [comment]
Предлагаю посылать пинг всегда, в независимости от IN_SCORE. Согласно функции void SV_EmitPings( sizebuf_t *msg ) посыл пинга занимает по 25 бит на каждого игрока. Тоесть при 10 игроках на сервере каждому из них будет послано дополнительно по 250 бит. К тому же все равно сам пинг считаецо каждый серверный фрейм.

**Comment by raub** [comment]
Тогда можно воспользоваться практикой хлтв_прокси в SV_ShouldUpdatePing, а именно:
qboolean SV_ShouldUpdatePing( sv_client_t *cl )
{
	if( host.realtime > cl->next_checkpingtime )
	{
		cl->next_checkpingtime = host.realtime + 1.0;
		return true;
	}
	return false;
}
теперь не важно хлтв или игрок - слать им пинг раз в секунду (было раз в 2 в оригинале).
это кстати (как и "посылать каждый фрейм") фиксит проблему что при первом открытии ТАБ пинги всё ещё 0, и только потом впервые присылаются.
