### ISSUE TITLE
Дисфункция лифта паровозика в начале сингла (где ракета)

### ISSUE THREAD

**Issue by raub** [mav745/CyberGamer#7]
Доезжаем до лифта, и... всё. Game over. Вагончик больше не движется, никогда.

**Comment by raub** [comment]
plats.cpp 2058
if ( !UseEnabled() )
	return;
if ( m_toggle_state == TS_AT_TOP )
	pTarget = m_trackTop;
...
стало
if ( !UseEnabled() )
	return;
Find();
if ( m_toggle_state == TS_AT_TOP )
	pTarget = m_trackTop;
Функция Find () уже наличествовала в CFuncTrackChange, но видимо никто и никогда не вызывал её, а потому m_trackTop и Bottom - не назначены (0x0), потому и вагончик не ехал.

**Comment by mav745** [comment]
Фикс должен происходит поправкой класса, функция которого ставицо на Think в коде Spawn-функции CFuncTrackChange   -   SetThink( &CFuncTrackTrain::Find );
